import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Home() {

  const router = useRouter()
  const [video, setVideo] = useState()

  useEffect(async () => {
    if (router.query.v) {
      const response = await fetch("/api/details?id=" + router.query.v)

      if (response.status == 400) {
        console.log("The requested video was not found")
      }
      else {
        const video = await response.json()
        setVideo(video)
      }
    }
  }, [router.query])

  return (
    <div className={styles.container}>
      <Head>
        <title>Youtube Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {video?.title}
        </h1>
        <img src={video?.img} alt="" />
        <button className={styles.button} onClick={() => router.push("/api/download/video/" + router.query.v)}>Download Video</button>
        <button className={styles.button} onClick={() => router.push("/api/download/audio/" + router.query.v)}>Download Audio</button>
      </main>
        
    </div>
  )
}
